# Generated by Django 5.1 on 2024-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_post_author_alter_post_head_image_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="blog/files/%Y/%m/%d/"),
        ),
    ]
